version: '3.7'

services:
  fluentd:
    image: ${REPO_NAME}/aftersales_fluentd:${FLUENTD_TAG_VERSION}
    volumes:
      - ./Logs/fluentd:/fluentd/log
      - ./Docker/fluentd/fluent.conf:/fluentd/etc/fluent.conf:ro
  elasticsearch:
    image: elasticsearch:7.4.2
    environment:
      - node.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=logsystem-cluster
      - xpack.monitoring.collection.enabled=true
      - xpack.ml.enabled=false
      - xpack.watcher.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  elasticsearch_slave:
    image: elasticsearch:7.4.2
    environment:
      - discovery.seed_hosts=elasticsearch
      - cluster.name=logsystem-cluster
      - xpack.monitoring.collection.enabled=true
      - xpack.ml.enabled=false
      - xpack.watcher.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: kibana:7.4.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  logstash:
    image: logstash:7.4.2
    depends_on:
      - elasticsearch

