metricbeat.modules:
- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s

fields:
  env: dev

output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["elasticsearch:9200"]