# https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-configuration-details.html

# https://www.elastic.co/guide/en/beats/filebeat/current/configuration-global-options.html
filebeat.spool_size: 2048
filebeat.idle_timeout: 30s

# https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html
filebeat.prospectors:
- input_type: log
  paths:
    - /mnt/log/*.log
  tags: ["winston"]  ## tags for the records
  fields:
    instance_id: "service_1" ## add extra metadata

# https://www.elastic.co/guide/en/beats/filebeat/current/logstash-output.html
output.logstash:
  hosts: ["logstash:5044"]